-- Для PostgreSQL оставляем как есть
-- Для H2 добавляем специальные комментарии

/* H2-SPECIFIC */ CREATE SCHEMA IF NOT EXISTS PUBLIC;

DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls CASCADE;

CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    /* H2-SPECIFIC */ url_id BIGINT /* PostgreSQL: INTEGER */ REFERENCES urls (id) ON DELETE CASCADE,
    status_code INTEGER,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP
);

--DROP TABLE IF EXISTS urls CASCADE;
--
--CREATE TABLE urls (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    name VARCHAR(255) NOT NULL,
--    created_at TIMESTAMP
--);
--
--DROP TABLE IF EXISTS url_checks;
--
--CREATE TABLE url_checks (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    url_id INTEGER REFERENCES urls (id) ON DELETE CASCADE,
--    status_code INTEGER,
--    title CHARACTER VARYING(255),
--    h1 CHARACTER VARYING(255),
--    description TEXT,
--    created_at TIMESTAMP
--);