DROP TABLE IF EXISTS urls CASCADE;

CREATE TABLE urls (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0)
);

DROP TABLE IF EXISTS url_checks;

CREATE TABLE url_checks (
    id INT PRIMARY KEY AUTO_INCREMENT,
    url_id INTEGER REFERENCES urls (id) ON DELETE CASCADE,
    status_code INTEGER,
    title CHARACTER VARYING(255),
    h1 CHARACTER VARYING(255),
    description TEXT,
    created_at TIMESTAMP(0)
);